# eshoppublicapi-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi-service
spec:
  selector:
    app: eshoppublicapi
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
