# eshopwebmvc-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: eshopwebmvc-service
spec:
  selector:
    app: eshopwebmvc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
